name: Test
on:
  pull_request:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - name: Install sample app deps
        working-directory: ./sample-app
        run: npm i
      - name: Test
        run: npm run test